files: ^.
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
    name: Trim Trailing Whitespace
    description: This hook trims trailing whitespace.
  - id: end-of-file-fixer
    name: Fix end of file issues
    description: This hook adds extra line to the end of the file.
  - id: check-yaml
    name: Check YAML files
    description: This hook checks any syntax errors in the YAML file.
  - id: check-case-conflict
    name: Check case conflict
    description: Check for files with names that would conflict on a case-insensitive filesystem like MacOS HFS+ or Windows FAT.
  - id: detect-private-key
    name: Detect private key
  - id: requirements-txt-fixer
    name: Fix requirements file
- repo: https://github.com/ambv/black
  rev: 22.3.0
  hooks:
    - id: black
      name: Format Python files
      description: Automatically format all the Python files based on PEP8.
