dataset:
  dataset_path: "../data/earthquakes/features.csv"
  label_path: "../data/earthquakes/matches_closed.csv"

pollutions:
  - name: "GaussianNoise"
    level: "column"
    column_names:
      - depth
    params:
      mean: 1.0
      std_dev: 0.0

  - name: "RoundingPolluter"
    level: "column"
    column_names:
      - azimuthal_gap
    params:
      decimal_places: 2
