pollutions:
  - name: "GaussianNoise"
    params:
      level: "column"
      indices:
        - depth
      mean: 1.0
      std_dev: 0.0

  - name: "GaussianNoise"
    params:
      level: "column"
      probability: 0.5
      mean: 1.0
      std_dev: 0.0

  - name: "Rounding"
    params:
      level: "column"
      indices:
        - "azimuthal_gap"
      decimal_places: 2

  - name: "Rounding"
    params:
      level: "column"
      probability: 0.5
      decimal_places: 2
