pollutions:
  # Gaussian Noise for depth measurements
  - name: "GaussianNoise"
    params:
      level: "column"
      mean: 1.0
      std_dev: 0.05  # 5% variation
    applicable_columns:
      - "depth"
      - "depth_uncertainty"
      - "horizontal_uncertainty"

  # Rounding for precision-sensitive measurements
  - name: "Rounding"
    params:
      level: "column"
      decimal_places: 2
    applicable_columns:
      - "depth"
      - "standard_error"
      - "azimuthal_gap"
      - "minimum_distance"
      - "mag_value"
      - "mag_uncertainty"

  # Scaling for depth and magnitude values
  - name: "ScalingShifting"
    params:
      level: "column"
      scale_amount: 1.1  # 10% increase
      shift_amount: 0.0
    applicable_columns:
      - "depth"
      - "mag_value"

  # MissingValue pollution
  - name: "MissingValue"
    params:
      level: "column"
      missing_ratio: 0.1  # 10% chance of being missing
    applicable_columns:
      - "depth_uncertainty"
      - "horizontal_uncertainty"
      - "standard_error"
      - "mag_uncertainty"
      - "mag_type"
      - "mag_station_count"
