pollutions:
  - name: "GaussianNoise"
    params:
      level: "column"
      mean: 1.0
      std_dev: 1.0
    applicable_columns:
      - "depth"
      - "depth_uncertainty"
      - "horizontal_uncertainty"
      - "used_phase_count"
      - "used_station_count"
      - "standard_error"
      - "azimuthal_gap"
      - "minimum_distance"
      - "mag_value"
      - "mag_uncertainty"
      - "mag_type"
      - "mag_station_count"

  - name: "GaussianNoise"
    params:
      level: "column"
      mean: 100.0
      std_dev: 10.0
    applicable_columns:
      - "depth"
      - "depth_uncertainty"
      - "horizontal_uncertainty"
      - "used_phase_count"
      - "used_station_count"
      - "standard_error"
      - "azimuthal_gap"
      - "minimum_distance"
      - "mag_value"
      - "mag_uncertainty"
      - "mag_type"
      - "mag_station_count"

  - name: "Rounding"
    params:
      level: "column"
      decimal_places: 1
    applicable_columns:
      - "depth"
      - "depth_uncertainty"
      - "horizontal_uncertainty"
      - "used_phase_count"
      - "used_station_count"
      - "standard_error"
      - "azimuthal_gap"
      - "minimum_distance"
      - "mag_value"
      - "mag_uncertainty"
      - "mag_type"
      - "mag_station_count"

  - name: "Rounding"
    params:
      level: "column"
      decimal_places: -1
    applicable_columns:
      - "depth"
      - "depth_uncertainty"
      - "horizontal_uncertainty"
      - "used_phase_count"
      - "used_station_count"
      - "standard_error"
      - "azimuthal_gap"
      - "minimum_distance"
      - "mag_value"
      - "mag_uncertainty"
      - "mag_type"
      - "mag_station_count"

  - name: "ScalingShifting"
    params:
      level: "column"
      scale_amount: 2.54
      shift_amount: 0.0
    applicable_columns:
      - "depth"
      - "depth_uncertainty"
      - "horizontal_uncertainty"
      - "used_phase_count"
      - "used_station_count"
      - "standard_error"
      - "azimuthal_gap"
      - "minimum_distance"
      - "mag_value"
      - "mag_uncertainty"
      - "mag_type"
      - "mag_station_count"

  - name: "ScalingShifting"
    params:
      level: "column"
      scale_amount: 1.8
      shift_amount: 32.0
    applicable_columns:
      - "depth"
      - "depth_uncertainty"
      - "horizontal_uncertainty"
      - "used_phase_count"
      - "used_station_count"
      - "standard_error"
      - "azimuthal_gap"
      - "minimum_distance"
      - "mag_value"
      - "mag_uncertainty"
      - "mag_type"
      - "mag_station_count"

  - name: "MissingValue"
    params:
      level: "column"
      missing_ratio: 1.0
    applicable_columns:
      - "depth"
      - "depth_uncertainty"
      - "horizontal_uncertainty"
      - "used_phase_count"
      - "used_station_count"
      - "standard_error"
      - "azimuthal_gap"
      - "minimum_distance"
      - "mag_value"
      - "mag_uncertainty"
      - "mag_type"
      - "mag_station_count"
